# Arquivo para navegação autônoma para a NARA
# Use use_sim_time: false para a cadeira física

# Publicador do mapa estático salvo
map_server:
  ros__parameters:
    use_sim_time: True
    frame_id: map   

amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: robot_footprint     
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: scan_filtered         

    # Começar conservador e reduzir depois de testar na cadeira física.
    alpha1: 0.2   # ruído rotacional causado por rotação
    alpha2: 0.2   # ruído rotacional causado por translação
    alpha3: 0.2   # ruído translacional causado por translação
    alpha4: 0.2   # ruído translacional causado por rotação

    # mais partículas = melhor cobertura de hipóteses
    min_particles: 500
    max_particles: 2000

    recovery_alpha_slow: 0.001   
    recovery_alpha_fast: 0.1     

    set_initial_pose: true       
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    update_min_d: 0.15           # distância mínima percorrida para reavaliar a pose
    update_min_a: 0.15           # rotação mínima para reavaliar a pose
    transform_tolerance: 0.4     


# Cérebro
bt_navigator:
  ros__parameters:
    use_sim_time: True
    odom_topic: "/noblenara/odom"
    robot_base_frame: robot_footprint
    global_frame: map
    #default_nav_to_pose_bt_xml
    #transform_tolerance # Possivel mudança na cadeira física


# Criadores dos mapas de custo
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      robot_base_frame: robot_footprint
      resolution: 0.05
      footprint: "[[-0.2, -0.3], [-0.2, 0.3], [0.85, 0.3], [0.85, -0.3]]"
      footprint_padding: 0.05
      transform_tolerance: 0.4

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      always_send_full_costmap: true

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true

      obstacle_layer: # Provavelmente trocar por voxel layer quando adicionar Câmera
        plugin: "nav2_costmap_2d::ObstacleLayer"
        track_unknown_space: true
        observation_sources: scan
        raytrace_max_range: 10.0 # Para RPLIDAR A2M12
        obstacle_max_range: 9.0

        scan:
          topic: /noblenara/scan_filtered
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: LaserScan

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 2.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: odom
      robot_base_frame: robot_footprint
      transform_tolerance: 0.4

      width: 6
      height: 6
      resolution: 0.05
      rolling_window: true

      footprint: "[[-0.2, -0.3], [-0.2, 0.3], [0.85, 0.3], [0.85, -0.3]]"
      footprint_padding: 0.05

      update_frequency: 10.0
      publish_frequency: 10.0


      plugins: ["obstacle_layer", "inflation_layer"]
      always_send_full_costmap: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        raytrace_max_range: 3.5 # Verificar!
        obstacle_max_range: 3.0

        scan:
          topic: /noblenara/scan_filtered
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: LaserScan

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 2.0


# Planejador global, retorna um caminho de acordo com o global_costmap
planner_server:
  ros__parameters:
    use_sim_time: True

    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid" # Navfn = Leve | Smac Planner Hibrid-A* = Potente, ideal
      minimum_turning_radius: 0.40
      allow_unknown: false
      max_iterations: 500000
      smooth_path: true
      motion_model_for_search: "DUBIN"


# Planejador local
# Tunar ou analisar posteriormente os plugins e os critics
controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    odom_topic: "/noblenara/odom"
    #failure_tolerance
    #speed_limit_topic: "/noblenara/speed_limit"

    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["goal_checker"]
    progress_checker_plugins: ["progress_checker"]
    

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 7.0

    # Verificar a mudança ou adição de StoppedGoalChecker --- A Cadeira para muito bruscamente perto do objetivo
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.35
      yaw_goal_tolerance: 0.4
      stateful: true

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 40
      model_dt: 0.05
      batch_size: 800
      vx_max: 1.0
      vx_min: 0.0
      wz_max: 0.8
      motion_model: "DiffDrive"

      critics: ["CostCritic", "PathAlignCritic", "PathFollowCritic", "GoalCritic", "GoalAngleCritic", "PreferForwardCritic"]

      CostCritic:
        enabled: true
        cost_weight: 3.81
        consider_footprint: true
        near_goal_distance: 0.6
        inflation_layer_name: "inflation_layer" # Existe um problema ao qual o MPPI não consegue achar o inflation layer mesmo com o setup correto; Versão 1.3.11

      PathAlignCritic:
        cost_weight: 14.0

      PathFollowCritic:
        cost_weight: 5.0

      GoalCritic:
        cost_weight: 5.0
        threshold_to_consider: 1.0

      GoalAngleCritic:
        cost_weight: 3.0
        threshold_to_consider: 0.5

      PreferForwardCritic:
        cost_weight: 2.0


# Comportamentos em Caso de Emergência (Robô Impossibilitado de Continuar)
behavior_server:
  ros__parameters:
    use_sim_time: True
    robot_base_frame: "robot_footprint"
    local_frame: "odom"
    global_frame: "map"
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"


# # Suavizador de Velocidade
# velocity_smoother:
#   ros__parameters:
#     smoothing_frequency: 20.0
#     feedback: "CLOSED_LOOP"                             # Testar na física se OPEN_LOOP é melhor (Referência de Odom vs Last Published)
#     max_velocity: [1.0, 0.0, 0.8]
#     min_velocity: [-0.0, 0.0, -0.8]
#     deadband_velocity: [0.0, 0.0, 0.0]                  # Velocidades Mínimas, Tunar na Cadeira Física!
#     max_accel: [0.5, 0.0, 0.4]
#     max_decel: [-0.25, 0.0, -0.25]
#     odom_topic: "/noblenara/odom"
#     stamp_smoothed_velocity_with_smoothing_time: false  # ONLY IN JAZZY


# Monitorador de Colisão
collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "robot_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "/noblenara/cmd_vel/raw"
    cmd_vel_out_topic: "/noblenara/cmd_vel"
    transform_tolerance: 0.5
    source_timeout: 2.0

    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/noblenara/scan_filtered"
      enabled: True

    polygons: ["SlowDown_Polygon", "Stop_Polygon"]

      # "[[-0.2, -0.3], [-0.2, 0.3], [0.85, 0.3], [0.85, -0.3]]" Default FootPrint do robot_footprint
    SlowDown_Polygon:
      type: "polygon"
      points: "[[-0.6, -0.9], [-0.6, 0.9], [1.65, 0.9], [1.65, -0.9]]" # Lateral = 0.6m | Frente = 0.8m | Costas = 0.4m (Sem contar o próprio Robô)
      # polygon_sub_topic: # Ouve o Tópico para definir os Pontos do Polígono
      action_type: "slowdown"
      slowdown_ratio: 0.6
      min_points: 4
      visualize: True
      enabled: True

    Stop_Polygon:
      type: "polygon"
      points: "[[-0.45, -0.55], [-0.45, 0.55], [1.20, 0.55], [1.20, -0.55]]" # Lateral = 0.25m | Frente = 0.35m | Costas = 0.15m (Sem contar o próprio Robô)
      # polygon_sub_topic: # Ouve o Tópico para definir os Pontos do Polígono
      action_type: "stop"
      min_points: 4
      visualize: True
      enabled: True

    # Velocity_Polygon:


# Lifecycle
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names:
      - controller_server
      - planner_server
      - bt_navigator
      - behavior_server
      - collision_monitor
